version: "3.7"

services:
  openswoole-bundle-test:
    container_name: openswoole-bundle-test
    build:
      context: .
      args:
        - OPENSWOOLE_VERSION=22.0.0
        - PHP_VERSION=8.1
        - COMPOSER_VERSION=2.5.5
    volumes:
      - .:/usr/src/openswoole-bundle
