services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    'OpenSwooleBundle\Bridge\Symfony\Bundle\Command\ServerStatusCommand':
        tags: [ { name: console.command, command: 'swoole:server:status' } ]

    'OpenSwooleBundle\Bridge\Symfony\Bundle\Command\ServerStopCommand':
        tags: [ { name: console.command, command: 'swoole:server:stop' } ]

    'OpenSwooleBundle\Bridge\Symfony\Bundle\Command\ServerReloadCommand':
        tags: [ { name: console.command, command: 'swoole:server:reload' } ]

    'swoole_bundle.server.http_server.configurator.for_server_start_command':
        class: OpenSwooleBundle\Server\Configurator\CallableChainConfigurator
        factory: ['@OpenSwooleBundle\Server\Configurator\CallableChainConfiguratorFactory', 'make']
        arguments:
            - '@swoole_bundle.server.http_server.configurator_collection'
            - '@swoole_bundle.server.http_server.configurator.with_request_handler'
        autoconfigure: false

    'OpenSwooleBundle\Bridge\Symfony\Bundle\Command\ServerStartCommand':
        tags: [ { name: console.command, command: 'swoole:server:start' } ]
        arguments:
            $serverConfigurator: '@swoole_bundle.server.http_server.configurator.for_server_start_command'

    'swoole_bundle.server.http_server.configurator.for_server_run_command':
        class: OpenSwooleBundle\Server\Configurator\CallableChainConfigurator
        factory: ['@OpenSwooleBundle\Server\Configurator\CallableChainConfiguratorFactory', 'make']
        arguments:
            - '@swoole_bundle.server.http_server.configurator_collection'
            - '@swoole_bundle.server.http_server.configurator.with_request_handler'
            - '@swoole_bundle.server.http_server.configurator.with_sigint_handler'
        autoconfigure: false

    'OpenSwooleBundle\Bridge\Symfony\Bundle\Command\ServerRunCommand':
        tags: [ { name: console.command, command: 'swoole:server:run' } ]
        arguments:
            $serverConfigurator: '@swoole_bundle.server.http_server.configurator.for_server_run_command'

    'swoole_bundle.server.http_server.configurator.for_server_profile_command':
        class: OpenSwooleBundle\Server\Configurator\CallableChainConfigurator
        factory: ['@OpenSwooleBundle\Server\Configurator\CallableChainConfiguratorFactory', 'make']
        arguments:
            - '@swoole_bundle.server.http_server.configurator_collection'
            - '@swoole_bundle.server.http_server.configurator.with_limited_request_handler'
            - '@swoole_bundle.server.http_server.configurator.with_sigint_handler'
        autoconfigure: false

    'OpenSwooleBundle\Bridge\Symfony\Bundle\Command\ServerProfileCommand':
        tags: [ { name: console.command, command: 'swoole:server:profile' } ]
        arguments:
            $serverConfigurator: '@swoole_bundle.server.http_server.configurator.for_server_profile_command'
