services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    OpenSwooleBundle\Component\AtomicCounter:
        factory: ['OpenSwooleBundle\Component\AtomicCounter', fromZero]

    OpenSwooleBundle\Component\ExceptionArrayTransformer:

    OpenSwooleBundle\Server\Middleware\MiddlewareInjector:

    OpenSwooleBundle\Server\RequestHandler\ExceptionHandler\ProductionExceptionHandler:

    OpenSwooleBundle\Server\RequestHandler\ExceptionHandler\JsonExceptionHandler:

    OpenSwooleBundle\Server\RequestHandler\ExceptionRequestHandler:
        arguments:
            $decorated: '@OpenSwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler'

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\SetRequestRuntimeConfiguration:

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInjectorInterface: '@OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector'

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector:
        arguments:
            $responseProcessor: '@response_processor.headers_and_cookies.streamed'

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface:
        class: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactory

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface:
        class: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessor

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor:
        decorates: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
        decoration_priority: -100
        arguments:
            - '@OpenSwooleBundle\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor.inner'

    response_processor.headers_and_cookies.default:
        class: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor
        decorates: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
        arguments:
            - '@response_processor.headers_and_cookies.default.inner'

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor:

    response_processor.headers_and_cookies.streamed:
        class: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor
        decorates: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor
        arguments:
            - '@response_processor.headers_and_cookies.streamed.inner'

    OpenSwooleBundle\Server\RequestHandler\RequestHandlerInterface:
        alias: OpenSwooleBundle\Server\RequestHandler\ExceptionRequestHandler

    OpenSwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler:

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorageFactory:

    OpenSwooleBundle\Server\RequestHandler\LimitedRequestHandler:

    OpenSwooleBundle\Server\LifecycleHandler\SigIntHandler:

    OpenSwooleBundle\Server\Runtime\CallableBootManagerFactory:

    OpenSwooleBundle\Server\Session\SwooleTableStorage:
        factory: ['OpenSwooleBundle\Server\Session\SwooleTableStorage', 'fromDefaults']

    OpenSwooleBundle\Server\Session\StorageInterface:
        alias: OpenSwooleBundle\Server\Session\SwooleTableStorage

    OpenSwooleBundle\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorage:

    OpenSwooleBundle\Server\Runtime\BootableInterface:
        class: OpenSwooleBundle\Server\Runtime\CallableBootManager
        factory: ['@OpenSwooleBundle\Server\Runtime\CallableBootManagerFactory', make]
        arguments: [!tagged 'swoole_bundle.bootable_service']
        autoconfigure: false

    OpenSwooleBundle\Server\HttpServer:

    OpenSwooleBundle\Server\WorkerHandler\WorkerStartHandlerInterface:
        class: OpenSwooleBundle\Server\WorkerHandler\NoOpWorkerStartHandler

    OpenSwooleBundle\Server\LifecycleHandler\ServerStartHandlerInterface:
        class: OpenSwooleBundle\Server\LifecycleHandler\NoOpServerStartHandler

    OpenSwooleBundle\Server\LifecycleHandler\ServerShutdownHandlerInterface:
        class: OpenSwooleBundle\Server\LifecycleHandler\NoOpServerShutdownHandler

    OpenSwooleBundle\Server\LifecycleHandler\ServerManagerStartHandlerInterface:
        class: OpenSwooleBundle\Server\LifecycleHandler\NoOpServerManagerStartHandler

    OpenSwooleBundle\Server\LifecycleHandler\ServerManagerStopHandlerInterface:
        class: OpenSwooleBundle\Server\LifecycleHandler\NoOpServerManagerStopHandler

    OpenSwooleBundle\Server\TaskHandler\TaskHandlerInterface:
        class: OpenSwooleBundle\Server\TaskHandler\NoOpTaskHandler

    OpenSwooleBundle\Server\TaskHandler\TaskFinishedHandlerInterface:
        class: OpenSwooleBundle\Server\TaskHandler\NoOpTaskFinishedHandler

    OpenSwooleBundle\Server\Api\ApiServerClientFactory:

    OpenSwooleBundle\Server\Api\ApiServerClient:
        factory: OpenSwooleBundle\Server\Api\ApiServerClientFactory:newClient

    OpenSwooleBundle\Server\Api\ApiServerInterface:
        class: OpenSwooleBundle\Server\Api\ApiServer

    #  Could be helpful for projects that uses/have included proxy-manager
    #        lazy: true
    #        tags:
    #            - { name: proxy, interface: OpenSwooleBundle\Server\Api\ApiServerInterface }

    OpenSwooleBundle\Server\Config\Sockets:

    OpenSwooleBundle\Server\HttpServerConfiguration:

    OpenSwooleBundle\Server\Configurator\WithHttpServerConfiguration:

    OpenSwooleBundle\Server\Configurator\WithServerShutdownHandler:

    OpenSwooleBundle\Server\Configurator\WithServerStartHandler:

    OpenSwooleBundle\Server\Configurator\WithServerManagerStartHandler:

    OpenSwooleBundle\Server\Configurator\WithServerManagerStopHandler:

    OpenSwooleBundle\Server\Configurator\WithWorkerStartHandler:

    OpenSwooleBundle\Server\Configurator\WithTaskHandler:

    OpenSwooleBundle\Server\Configurator\WithTaskFinishedHandler:

    OpenSwooleBundle\Server\Configurator\CallableChainConfiguratorFactory:

    OpenSwooleBundle\Server\Api\WithApiServerConfiguration:
        arguments:
            $requestHandler: '@swoole_bundle.server.api_server.request_handler'

    OpenSwooleBundle\Server\Api\ApiServerRequestHandler:

    swoole_bundle.server.api_server.request_handler:
        class: OpenSwooleBundle\Server\RequestHandler\ExceptionRequestHandler
        arguments:
            $decorated: '@OpenSwooleBundle\Server\Api\ApiServerRequestHandler'

    swoole_bundle.server.http_server.configurator_collection:
        class: OpenSwooleBundle\Component\GeneratedCollection
        arguments: [!tagged 'swoole_bundle.server_configurator']

    OpenSwooleBundle\Server\Configurator\ConfiguratorInterface:
        alias: swoole_bundle.server.http_server.configurator

    swoole_bundle.session.table_storage:
        alias: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorage

    swoole_bundle.session.table_storage_factory:
        alias: OpenSwooleBundle\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorageFactory

    swoole_bundle.server.http_server.configurator.with_request_handler:
        class: OpenSwooleBundle\Server\Configurator\WithRequestHandler
        autoconfigure: false

    swoole_bundle.server.http_server.configurator.with_limited_request_handler:
        class: OpenSwooleBundle\Server\Configurator\WithRequestHandler
        autoconfigure: false
        arguments:
            $requestHandler: '@OpenSwooleBundle\Server\RequestHandler\LimitedRequestHandler'

    swoole_bundle.server.http_server.configurator.with_sigint_handler:
        class: OpenSwooleBundle\Server\Configurator\WithServerStartHandler
        autoconfigure: false
        arguments:
            $handler: '@OpenSwooleBundle\Server\LifecycleHandler\SigIntHandler'
